### PR TITLE
Add support for hidpi displays

### PR DESCRIPTION
**Pull request by mwylde**
Addresses #2

### CODE REVIEW

**Comment by Be-ing** [comment]
Unfortunately this still looks tiny. I am using GNOME 3.38 on Wayland with Fedora 33. I don't know how Skia determines the scale factor or how I can set that. I can't find any documentation about that.

**Comment by mwylde** [comment]
The relevant library here is actually sdl2, not skia. Sdl2 is responsible for creating the window at the desired (logical) size (800x600 by default) and reporting back the correct size in screen pixels (to the `window.size()` call) and in logical pixels (`window.drable_size()`). In  From your screenshot, it looks like sdl is not able to determine that the display is scaled (my guess is that here: https://github.com/mwylde/loopers/pull/3/commits/57ef600c3818ad2802b80245a780a25843911a8b#diff-29373c8db8084fd64846b91d61b7aae833ca30a7f251a8d8988e216775c26609L101 where we compute the scale factor, we would get 1 for your display).

Acorrding to [this article](https://www.phoronix.com/scan.php?page=news_item&px=SDL2-Wayland-HiDPI-Support) sdl added support in 2.0.10 for hidpi on wayland. Can you check your libsdl2 version?

**Comment by Be-ing** [comment]
I am using SDL2-2.0.12-4.fc33.x86_64

**Comment by Be-ing** [comment]
Qt has an environment variable that users can set to scale applications. Is there anything comparable for SDL? I can't find any documentation.

**Comment by mwylde** [comment]
Yeah, I also can't find any more information. This PR renders hidpi correctly on MacOS, so I think from the usage side things are correct. At this point this looks like a sdl problem and not a loopers bug, so I'm going to close. If you figure anything else out about getting this to work on wayland please report back!

**Pull request merged**
